### PR TITLE
remove deprecation warning

### PR DESCRIPTION
**Pull request by jlambert121**
The HERE weather integration has a deprecation warning that will prevent it from function in 2023.1.

https://developers.home-assistant.io/blog/2022/10/14/deprecate-unit-system

### CODE REVIEW

**Comment by jlambert121** [comment]
Looks like there's a lot more with this I missed after cleaning up the warnings from this.  I'll try to look at reworking it and updating soon.

**Comment by eifinger** [comment]
Thank you for your contribution. Be aware that there are some generell issues with this integration currently: https://github.com/eifinger/hass-here-weather/issues/174

**Comment by jlambert121** [comment]
Hm, all right.  I haven't done python dev before so will need to see about getting an environment set up.

**Comment by jlambert121** [comment]
This is probably the limit of what I can contribute to this given the time I have and my lack of knowledge of custom components in HA, feel free to close if it isn't helpful.

TODO: 
Accessing the `name` attribute is no longer supported: https://github.com/eifinger/hass-here-weather/blob/main/custom_components/here_weather/sensor.py#L54 
How does the new unit system impact [these](https://github.com/eifinger/hass-here-weather/blob/main/custom_components/here_weather/const.py#L117) in the constants?

**Comment by eifinger** [comment]
Thank you for your contribution.
I will use it as a base for further development.

Unfortunately this is currently blocked until homeassistant uses aiohttp 3.8.3 or later since aiohere depends on it

**Comment by jlambert121** [comment]
No problem. Do you end up with a bit of a chicken and egg where they need to go together since this will break in 2023.1?

**Comment by eifinger** [comment]
Yes, it will break in 2023.1 I hope the issues in homeassistant with aiohttp will be fixed by then

**Comment by eifinger** [comment]
The HERE API changed **ALOT** https://github.com/eifinger/hass-here-weather/pull/188

**Comment by eifinger** [comment]
Thank you for your contribution. It helped a lot!

**Pull request closed without merging**
